version: '3.8'

services:
  guestbook-service:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: 402261700458.dkr.ecr.ap-northeast-2.amazonaws.com/guestbook-app:1.0
    container_name: guestbook-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - DB_HOST=postgres.cmscmvup6oie.ap-northeast-2.rds.amazonaws.com
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
#      - AWS_ACCESS_KEY=...
#      - AWS_SECRET_KEY=...
      - AWS_REGION=ap-northeast-2
      - AWS_S3_BUCKET=guestbook-app-1
      - AWS_S3_BASE_URL=https://guestbook-app-1.s3.ap-northeast-2.amazonaws.com